name: nmv
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    #- uses: actions/checkout@v2
    - name: Fetch
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nmv/master/run.sh -OutFile run.sh
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nmv/master/rest.sh -OutFile rest.sh
    - name: Initial Setup.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: source run.sh "user1" "user1" "$NGROK_AUTH_TOKEN"
    - name: ngrok supplying VNC on.. (username:user1/password:user1)
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: rest
      run: source rest.sh
